//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ultimatexr : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean joystick_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_joystick_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick2_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_joystick2_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_trigger_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger2_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_trigger2_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_grip_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button1_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button1_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button2_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button2_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button3_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button3_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button4_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button4_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean bumper_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_bumper_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean bumper2_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_bumper2_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean back_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_back_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_menu_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean thumbcapsense_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_thumbcapsense_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean indexcapsense_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_indexcapsense_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean middlecapsense_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_middlecapsense_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean ringcapsense_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_ringcapsense_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean littlecapsense_click_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_littlecapsense_click_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_joystick_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick2_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_joystick2_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_trigger_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger2_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_trigger2_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_grip_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button1_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button1_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button2_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button2_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button3_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button3_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean button4_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_button4_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean bumper_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_bumper_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean bumper2_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_bumper2_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean back_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_back_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_menu_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean thumbcapsense_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_thumbcapsense_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean indexcapsense_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_indexcapsense_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean middlecapsense_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_middlecapsense_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean ringcapsense_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_ringcapsense_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Boolean littlecapsense_touch_boolean
        {
            get
            {
                return SteamVR_Actions.ultimatexr_littlecapsense_touch_boolean;
            }
        }
        
        public virtual SteamVR_Action_Single grip_vector1
        {
            get
            {
                return SteamVR_Actions.ultimatexr_grip_vector1;
            }
        }
        
        public virtual SteamVR_Action_Single trigger_vector1
        {
            get
            {
                return SteamVR_Actions.ultimatexr_trigger_vector1;
            }
        }
        
        public virtual SteamVR_Action_Single trigger2_vector1
        {
            get
            {
                return SteamVR_Actions.ultimatexr_trigger2_vector1;
            }
        }
        
        public virtual SteamVR_Action_Vector2 joystick_vector2
        {
            get
            {
                return SteamVR_Actions.ultimatexr_joystick_vector2;
            }
        }
        
        public virtual SteamVR_Action_Vector2 joystick2_vector2
        {
            get
            {
                return SteamVR_Actions.ultimatexr_joystick2_vector2;
            }
        }
        
        public virtual SteamVR_Action_Skeleton hand_left_skeleton
        {
            get
            {
                return SteamVR_Actions.ultimatexr_hand_left_skeleton;
            }
        }
        
        public virtual SteamVR_Action_Skeleton hand_right_skeleton
        {
            get
            {
                return SteamVR_Actions.ultimatexr_hand_right_skeleton;
            }
        }
        
        public virtual SteamVR_Action_Vibration hand_haptics
        {
            get
            {
                return SteamVR_Actions.ultimatexr_hand_haptics;
            }
        }
    }
}
