name: GothicVR Release Job

on:
  release:
    types:
      - created


jobs:
  #########
  # BUILD #
  #########

  buildForAllPlatforms:
    name: Build GothicVR for ${{ matrix.targetDevice }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: StandaloneWindows64
            targetDevice: Windows64
#          - targetPlatform: Android
#            targetDevice: Pico
#          - targetPlatform: Android
#            targetDevice: Quest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
          clean: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
          buildMethod: GVR.Editor.UnityBuildTools.UnityBuilderAction.Perform${{ matrix.targetDevice }}Build

      # Release
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: Build-${{ matrix.targetDevice }}
          asset_path: build/${{ matrix.targetDevice }}
          asset_content_type: binary/octet-stream


#      - uses: actions/upload-artifact@v2
#        with:
#          name: Build-${{ matrix.targetDevice }}
#          path: build/${{ matrix.targetDevice }}
#          expire-in: 2 days
